avantifellows/db-service

lib/dbservice/users.ex, lib/dbservice/users/user.ex, lib/dbservice_web/controllers/fallback_controller.ex, lib/dbservice_web/controllers/user_controller.ex, lib/dbservice_web/router.ex, lib/dbservice_web/views/changeset_view.ex, lib/dbservice_web/views/user_view.ex, priv/repo/migrations/20220329180317_create_user.exs, test/dbservice/users_test.exs, test/dbservice_web/controllers/user_controller_test.exs, test/support/fixtures/users_fixtures.ex
1. Controller, schema (model), and migrations for User
2. User right now have columns from [DB schema](https://whimsical.com/af-db-schema-8MT1bQVfQx4SqffSYPKiKm)
3. Boilerplate code for user test cases, fixtures, fallback controller etc that got added when ran the following command:
```sh
mix phx.gen.json Users User user first_name:string last_name:string email:string phone:string gender:string address:text city:string district:string state:string pincode:string role:string
```
4. User REST API endpoint has been added to Postman
1. Test cases will be worked on later after a basic workflow is in place
=> User API init

README.md, docs/DEPLOYMENT.md, docs/INSTALLATION.md, lib/dbservice_web/router.ex
1. Installation guide update for Phoenix setup
2. Documentation for GIgalixir deployment guidelines
=> Installation + Gigalixir Deployment docs

lib/dbservice/sessions.ex, lib/dbservice/sessions/session_occurence.ex, lib/dbservice/sessions/user_session.ex, lib/dbservice_web/controllers/user_controller.ex, lib/dbservice_web/controllers/user_session_controller.ex, lib/dbservice_web/router.ex, lib/dbservice_web/views/session_occurence_view.ex, lib/dbservice_web/views/user_session_view.ex
Targets #10 
1. User session mapping
2. User session endpoints for CRUD operations
3. Sending users for a session occurrence along with session occurrence data - only for single session occurrence API call
=> #10 User session mapping with additional data

lib/dbservice/batches.ex, lib/dbservice/batches/batch.ex, lib/dbservice/sessions.ex, lib/dbservice/sessions/session.ex, lib/dbservice_web/controllers/batch_controller.ex, lib/dbservice_web/controllers/session_controller.ex, lib/dbservice_web/router.ex, priv/repo/migrations/20220429194407_create_batch_session.exs
More API endpoints for:
1. Batch bulk update sessions
2. Session bulk update batches
3. Correction in batch session migration for batch instead of the user. Will have to refresh migrations and recreate DB.
4. Hyphenated URLs
=> Batch & Session APIs

lib/dbservice_web/controllers/batch_controller.ex, lib/dbservice_web/controllers/enrollment_record_controller.ex, lib/dbservice_web/controllers/group_controller.ex, lib/dbservice_web/controllers/school_controller.ex, lib/dbservice_web/controllers/session_controller.ex, lib/dbservice_web/controllers/session_occurence_controller.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/controllers/teacher_controller.ex, lib/dbservice_web/controllers/user_controller.ex, lib/dbservice_web/views/batch_view.ex, lib/dbservice_web/views/enrollment_record_view.ex, lib/dbservice_web/views/group_view.ex, lib/dbservice_web/views/school_view.ex, lib/dbservice_web/views/session_occurence_view.ex, lib/dbservice_web/views/session_view.ex, lib/dbservice_web/views/student_view.ex, lib/dbservice_web/views/teacher_view.ex, lib/dbservice_web/views/user_view.ex
Targets #14
1. Updated request JSON structure for every available endpoint by removing the entity key (user, session, etc) at top level
2. Updated response JSON structure for every endpoint by removing "data" key at top level
3. Updated Postman collection
=> #14 JSON structure updates

lib/dbservice/sessions/session.ex, lib/dbservice/sessions/session_occurence.ex, lib/dbservice_web/views/enrollment_record_view.ex, lib/dbservice_web/views/session_view.ex, lib/dbservice_web/views/student_view.ex, lib/dbservice_web/views/teacher_view.ex
1. Added some missing fields in the response data for session, enrollment record, student and teacher
2. Added some missing fields in the request data (cast) for session and session occurrence.
=> Response data updates

lib/dbservice/group_sessions.ex, lib/dbservice/groups.ex, lib/dbservice/groups/group_session.ex, lib/dbservice/groups/group_user.ex, lib/dbservice/sessions.ex, lib/dbservice/sessions/session.ex, lib/dbservice/users.ex, lib/dbservice/users/user.ex, lib/dbservice_web/controllers/group_controller.ex, lib/dbservice_web/controllers/session_controller.ex, lib/dbservice_web/controllers/user_controller.ex, lib/dbservice_web/router.ex, lib/dbservice_web/swagger_schemas/common.ex, lib/dbservice_web/swagger_schemas/group.ex, lib/dbservice_web/views/enrollment_record_view.ex, lib/dbservice_web/views/group_view.ex, lib/dbservice_web/views/school_view.ex, lib/dbservice_web/views/session_view.ex, lib/dbservice_web/views/student_view.ex, lib/dbservice_web/views/user_view.ex, priv/static/swagger.json
- Modified controllers for the latest schema update
- Modified Swagger
- Modified api's
=> Modification of swagger and controllers for the latest schema update

lib/dbservice/groups/group.ex, lib/dbservice/groups/group_session.ex, lib/dbservice/groups/group_user.ex, lib/dbservice/schools/enrollment_record.ex, lib/dbservice/sessions/session.ex, lib/dbservice/sessions/session_occurence.ex, lib/dbservice/sessions/user_session.ex, lib/dbservice/users/student.ex, lib/dbservice/users/user.ex, lib/dbservice/utils/util.ex, lib/dbservice_web/controllers/group_controller.ex, lib/dbservice_web/controllers/school_controller.ex, lib/dbservice_web/swagger_schemas/student.ex, lib/dbservice_web/views/student_view.ex, priv/repo/migrations/20221018090238_modify_group_user.exs, priv/repo/migrations/20221018090242_modify_group_session.exs, priv/repo/migrations/20221022100755_modify_student.exs, priv/repo/migrations/20221026071256_modify_user.exs, priv/repo/seeds.exs, priv/static/swagger.json
#40 
- Updated Schema
- Modified group_user and group_session migration by adding a default value (which will be equivalent to the current date and time) to the inserted_at and updated_at fields because timestamps() were unable to fill those fields by itself
-  Added validation to some fields
- Modified seeder
=> Minor schema changes

lib/dbservice/groups/group.ex, lib/dbservice/groups/group_user.ex, lib/dbservice/schools/enrollment_record.ex, lib/dbservice/sessions/session.ex, lib/dbservice/sessions/session_occurence.ex, lib/dbservice/sessions/user_session.ex, lib/dbservice/users/user.ex, lib/dbservice_web/swagger_schemas/user.ex, lib/dbservice_web/views/user_view.ex, priv/static/swagger.json
- Added conditions to validation
- Updated required fields in schema
- Modified swagger
=> Conditional Validations

lib/dbservice/sessions/session.ex, priv/repo/migrations/20221105060429_modify_uuid_in_session.exs
- Changed type of uuid from binary_id to string
- Created migration for the modification above
=> Changing type of UUID in session table and schema

lib/dbservice/sessions/session.ex, lib/dbservice/users/student.ex, lib/dbservice_web/controllers/session_controller.ex, lib/dbservice_web/controllers/user_controller.ex, lib/dbservice_web/views/session_view.ex, lib/dbservice_web/views/student_view.ex, priv/repo/migrations/20221121095220_modify_uuid_in_student.exs, priv/repo/migrations/20221121103216_rename_uuid_in_session.exs, priv/repo/seeds.exs
- Added query to filter results
- Modified migrations
=> Added filter query!

lib/dbservice/users.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/controllers/teacher_controller.ex, lib/dbservice_web/router.ex, lib/dbservice_web/views/teacher_view.ex
- Created an API which creates & updates a student with a user
- Created an API which creates & updates a teacher with a user
=> API to create & update student with a user and teacher with a user

lib/dbservice/groups/group.ex, lib/dbservice/groups/group_user.ex, lib/dbservice/sessions/session.ex, priv/repo/migrations/20221126055647_add_auth_type_to_group.exs, priv/repo/seeds.exs
- Remove validations for date form group, session and group_user
- Added "auth_type" to group
- Added "group" to type in group schema
=> remove validations from suggested places

lib/dbservice_web/controllers/enrollment_record_controller.ex, lib/dbservice_web/controllers/group_controller.ex, lib/dbservice_web/controllers/school_controller.ex, lib/dbservice_web/controllers/session_occurence_controller.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/controllers/teacher_controller.ex
- Added filters to all contexts
=> added filters to contexts!

lib/dbservice_web/controllers/enrollment_record_controller.ex, lib/dbservice_web/controllers/group_controller.ex, lib/dbservice_web/controllers/school_controller.ex, lib/dbservice_web/controllers/session_controller.ex, lib/dbservice_web/controllers/session_occurence_controller.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/controllers/teacher_controller.ex, lib/dbservice_web/controllers/user_controller.ex, lib/dbservice_web/views/student_view.ex, lib/dbservice_web/views/teacher_view.ex
- Modified filters
- Modified controller to show student with user
- Modified controller to show teacher with user
=> added changes to filter and view

lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/controllers/teacher_controller.ex
- Render single student with user and single teacher with user on posting a new registration
=> Render single student-user & teacher-user on registration

lib/dbservice_web/controllers/group_controller.ex
- Removed redundant index function for group controller
=> Removed group index

lib/dbservice/groups/group.ex, lib/dbservice/schools/enrollment_record.ex, lib/dbservice/users/student.ex, lib/dbservice/users/user.ex, lib/dbservice_web/views/enrollment_record_view.ex, lib/dbservice_web/views/group_view.ex, lib/dbservice_web/views/student_view.ex, lib/dbservice_web/views/user_view.ex, priv/repo/migrations/20230103081843_add_column_to_student.exs, priv/repo/migrations/20230103084345_add_column_to_group.exs, priv/repo/migrations/20230103084735_add_column_to_user.exs, priv/repo/migrations/20230111080506_add_column_to_enrollment_record.exs, priv/repo/seeds.exs
- Added additional fields to schema (program_model, is_dropper, country, course, contact_hours_per_week)
- Added seeders for the newly added fields
=> Added fields to schema

lib/dbservice/groups/group.ex, lib/dbservice_web/plugs/domain_whitelist_plug.ex, lib/dbservice_web/swagger_schemas/group.ex, lib/dbservice_web/views/group_view.ex, priv/repo/migrations/20230203064023_add_group_id_in_group.exs, priv/repo/seeds.exs, priv/static/swagger.json
- Added group_id to group table
=> Addition of group_id in group table

lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/controllers/user_controller.ex
- Added limit in student controller
- Added limit in user controller
=> Added limit to query result in student and user

lib/dbservice/sessions/session.ex, lib/dbservice_web/views/session_view.ex, priv/repo/migrations/20230223064132_add_columns_to_session.exs, priv/repo/seeds.exs
- Added platform_id to session
=> Added platform id to session

lib/dbservice_web/controllers/group_session_controller.ex, lib/dbservice_web/controllers/user_session_controller.ex
- Added filters for group-session
- Added filters for user-session
=> Added filters for group-session and user-session

lib/dbservice_web/controllers/user_session_controller.ex
- Modified the update function in user session
=> Modified the update function in user session

lib/dbservice/sessions/session_occurence.ex, lib/dbservice_web/views/session_occurence_view.ex, priv/repo/migrations/20230309114643_rename_session_id_in_session_occurrence.exs, priv/repo/migrations/20230309115709_add_session_id_in_session_occurrence.exs, priv/repo/migrations/20230309121809_add_unique_constraint_to_session_id_in_session_table.exs, priv/repo/seeds.exs
- Added session_id and renamed existing session_id as session_fk in session_occurrence table
- Added unique index to session_id in session table
- Modified views
=> Modified session and session-occurrence table

lib/dbservice_web/controllers/teacher_controller.ex, lib/dbservice_web/swagger_schemas/teacher.ex, priv/static/swagger.json
- Added swagger docs for teacher with user
=> Added swagger docs for teacher with user

lib/dbservice_web/controllers/teacher_controller.ex, lib/dbservice_web/views/teacher_view.ex
- Modified teacher views to show teacher with a user
=> Show teacher with user

priv/repo/migrations/20230314140954_rename_session_occurence_to_session_occurrence.exs
- Renamed session_occurence to session_occurrence
=> Renamed session_occurence to session_occurrence

lib/dbservice/sessions/session_occurence.ex, lib/dbservice_web/router.ex
- Modified route for session-occurrence
=> Modified route for session occurrence

lib/dbservice/users/teacher.ex, lib/dbservice_web/controllers/user_session_controller.ex
- Updated user-session create function
- Removed school_id from validated fields
=> Updated user-session controller

lib/dbservice/sessions/user_session.ex, lib/dbservice/users/user.ex, lib/dbservice_web/views/user_session_view.ex, priv/repo/migrations/20230320064301_remove_user_id_from_user_session.exs, priv/repo/migrations/20230320070542_rename_session_occurence_to_session_occurrence_in_user_session.exs, priv/repo/seeds.exs
- Removed user_id
- Added is_user_valid
- Modified user_session views
- Modified seeds.exs
=> Modified user_session

lib/dbservice/sessions/user_session.ex, lib/dbservice/utils/util.ex, lib/dbservice_web/views/user_session_view.ex, priv/repo/migrations/20230320085121_add_user_id_in_user_session.exs, priv/repo/seeds.exs
- Added user_id while removing references
- Modified validation over start_time and end_time
- Modified views and seeder based on the changes
=> Added user_id in user session

lib/dbservice_web/swagger_schemas/session.ex, lib/dbservice_web/swagger_schemas/student.ex, lib/dbservice_web/swagger_schemas/user_session.ex, priv/static/swagger.json
=> Modified user-session swagger docs

lib/dbservice_web/controllers/batch_controller.ex, lib/dbservice_web/controllers/batch_program_controller.ex, lib/dbservice_web/controllers/group_controller.ex, lib/dbservice_web/controllers/group_session_controller.ex, lib/dbservice_web/controllers/group_type_controller.ex, lib/dbservice_web/controllers/program_controller.ex, lib/dbservice_web/controllers/school_controller.ex, lib/dbservice_web/controllers/session_controller.ex, lib/dbservice_web/controllers/session_occurence_controller.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/controllers/teacher_controller.ex, lib/dbservice_web/controllers/user_controller.ex, lib/dbservice_web/controllers/user_session_controller.ex, priv/static/swagger.json
- Modified query params of swagger docs
=> Modified query params of swagger docs

config/prod.exs
- Removed `Increase timeout time` configurations
- Removed `Plug.SSL` configurations
=> Removed unwanted configurations (fixed SSL error)

lib/dbservice_web/controllers/session_occurence_controller.ex, priv/static/swagger.json
- Resolved session occurrence swagger docs error
=> Resolved session occurrence swagger error

fetch-data.sh
Script that fetches a data dump from a production PostgreSQL database and restores it to a local PostgreSQL database. It also removes the dump file after the restoration is complete.
To run the script you need to run the following command in the terminal:
`
./fetch-data.sh
`
=> Restore production database to local database

lib/dbservice/sessions.ex, lib/dbservice/sessions/session.ex, lib/dbservice_web/controllers/session_controller.ex
- fixed group session functionality based on latest schema changes
=> fixed group session functionality based on latest schema changes

lib/dbservice/users.ex, lib/dbservice/users/user.ex, lib/dbservice_web/controllers/user_controller.ex, lib/dbservice_web/router.ex
- fixed group session functionality based on latest schema changes
=> fixed group user functionality as per the latest schema changes

.github/workflows/staging_deploy.yml
=> Fix branch name changes

priv/repo/migrations/20230623093600_change_session_columns.exs, priv/repo/migrations/20230623100328_change_session_two_columns.exs
1. Change the data type of these columns `activate_signup` , `id_generation`
=> New migration for session table

config/dev.exs, config/prod.exs, lib/dbservice_web/controllers/enrollment_record_controller.ex, lib/dbservice_web/controllers/session_controller.ex, lib/dbservice_web/router.ex
**Description**
- Fixed swagger base url
**Checklist**
=> Fixed swagger Base url

.github/workflows/production_deploy.yml, .github/workflows/staging_deploy.yml, .gitignore, lib/dbservice_web/endpoint.ex, lib/dbservice_web/plugs/authentication_middleware_plug.ex, mix.exs, priv/repo/migrations/20230630100806_alter_student_table_column.exs
#130 
- Added authentication middleware in order to whitelist specific users
- We can create a custom plug which checks the 'Authorization' header of incoming HTTP requests to ensure that
it matches a predefined API key stored in the 'BEARER_TOKEN' environment variable.
=> Authentication middleware

.gitignore, config/config.exs, config/prod.exs, config/runtime.exs, mix.exs
#126 
- Made the application to log in a separate file which could be later on used in cloudwatch
=> Logging access logs to separate file

lib/dbservice/batches.ex, lib/dbservice/exams.ex, lib/dbservice/group_sessions.ex, lib/dbservice/groups.ex, lib/dbservice/sessions.ex, lib/dbservice/users.ex, lib/dbservice_web/controllers/batch_controller.ex, lib/dbservice_web/controllers/exam_controller.ex, lib/dbservice_web/controllers/group_controller.ex, lib/dbservice_web/controllers/group_session_controller.ex, lib/dbservice_web/controllers/session_controller.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/controllers/teacher_controller.ex
The `db-service` checks:
-  if a new session needs to be created or an existing session can be updated based on the session ID.
- if a new student needs to be created or an existing student can be updated based on the student ID.
-  if a new group-session needs to be created or an existing group-session can be updated based on the session ID.
-  if a new batch needs to be created or an existing batch can be updated based on the batch ID.
- if a new teacher needs to be created or an existing teacher can be updated based on the teacher ID.
- if a new exam needs to be created or an existing exam can be updated based on the exam name.
- if a new group needs to be created or an existing group can be updated based on the group name.
=> Creation of new resource or updation of resources is now dependant on the db-service

lib/dbservice/schools.ex, lib/dbservice_web/controllers/school_controller.ex
This PR introduces a new feature related to school creation and updating. The primary focus is on handling both new school creation and updates efficiently.
- **SchoolController:**
- Implemented logic to check for existing schools with the same code.
- Modified the `create` action to handle both new school creation and updates.
- **Schools Module:**
- Updated the module to include a `get_school_by_code` function.
=> Feat: implemented school creation and updation efficiently

.github/workflows/staging_deploy.yml
=> Hotfix: Staging CD pipeline

mix.exs
- Downgraded `phoenix_live_dashboard
=> Fix: Dependency error in CD

docs/INSTALLATION.md
- Added ElixirLS extension link in readme
=> Feat: Added editor support in README

docs/INSTALLATION.md
- Added ElixirLS support matrix
=> Feat: Updated Readme

lib/dbservice/enrollment_record/enrollment_record.ex, lib/dbservice/enrollment_records.ex, lib/dbservice/group_users.ex, lib/dbservice/sessions/session_occurence.ex, lib/dbservice/utils/util.ex, lib/dbservice_web/controllers/group_user_controller.ex
Whenever a group-user is created, an enrollment record is automatically created.
=> create ER on group-user creation

lib/dbservice/group_sessions.ex, lib/dbservice/group_users.ex, lib/dbservice/groups.ex, lib/dbservice_web/controllers/user_controller.ex, lib/dbservice_web/router.ex, lib/dbservice_web/views/user_view.ex
- Now we have a support of an API which will allow us to fetch all the live classes and quiz sessions belonging to the logged in user in gurukul
=> Feat: API to retrieve sessions belonging to a user

lib/dbservice/statuses.ex, lib/dbservice/statuses/status.ex, lib/dbservice/users/student.ex, lib/dbservice_web/controllers/status_controller.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/router.ex, lib/dbservice_web/swagger_schemas/status.ex, lib/dbservice_web/views/status_view.ex, lib/dbservice_web/views/student_view.ex, priv/repo/migrations/20240606051945_add_status_to_student.exs, priv/repo/migrations/20240606142846_create_status_table.exs
https://www.notion.so/avantifellows/ADR-Dropout-Students-Handling-b31ca1a7e5574df996798e8a5a63de44
- Added `status` schema, migrations, controller, and view
- Updated `student` view
- Added `dropout` endpoint
- Added logic to remove all the `group-user` entries
- Added logic to create new ER for dropout students
- Added logic to update the `status` field in student to `dropout`
=> Feature: Dropout Student Handling

lib/dbservice/products.ex, lib/dbservice/programs.ex, lib/dbservice_web/controllers/product_controller.ex, lib/dbservice_web/controllers/program_controller.ex
- Modified program_controller to check if program exists, then update or create
- Modified product_controller to check if product exists, then update or create
=> Add upsert functionality:

lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/router.ex
- Added an enpoint which:
- Creates an entry in group-user for the current batch enrollment
- Creates two entries in the enrollment record: one for the current batch enrollment and one for the current status
- Set's student status to "enrolled"
=> Feat: Funtionality mark student as enrolled

lib/dbservice/school_batches.ex, lib/dbservice/school_batches/school_batch.ex, lib/dbservice_web/controllers/school_batch_controller.ex, lib/dbservice_web/router.ex, lib/dbservice_web/swagger_schemas/school.ex, lib/dbservice_web/views/school_batch_view.ex, priv/repo/migrations/20240705094637_create_school_batch_table.exs
- https://www.notion.so/avantifellows/ADR-Mapping-Multiple-Batches-to-a-School-53dcf131002d4754a4ea1931846264b4
- Added school-batch migration, schema, context, view, swagger and controller files
=> Feat: School-Batch Table

lib/dbservice/schools.ex, lib/dbservice/schools/school.ex, lib/dbservice/users/user.ex, lib/dbservice_web/controllers/school_controller.ex, lib/dbservice_web/router.ex, lib/dbservice_web/swagger_schemas/school.ex, lib/dbservice_web/views/school_view.ex, priv/repo/migrations/20240711052952_add_user_id_to_school.exs
- Added `user_id` to school
- Added an endpoint to create school with user
=> Feat: Add user_id to school

lib/dbservice_web/controllers/teacher_controller.ex, lib/dbservice_web/views/teacher_view.ex
- Show subject_id in place of subject
- Fixed `function clause error` for updation
=> Fix: Teacher View

lib/dbservice_web/controllers/session_controller.ex
Added filter params in session api using
- group (i.e. auth_group)
- parent_id (i.e. parent Batch)
- batch_id (i.e. sub batch)
=> add: session filters

lib/dbservice_web/views/school_view.ex
- Deploying `invalidate_future_date` to prod
=> Prod deployment

lib/dbservice/utils/util.ex, lib/dbservice_web/controllers/session_controller.ex
- Deploying `is_quiz` filter to prod
=> Prod deployment: `is_quiz` filter

lib/dbservice/sessions.ex, lib/dbservice/sessions/session.ex, lib/dbservice/sessions/session_occurence.ex, lib/dbservice/users/user.ex, lib/dbservice_web/controllers/session_occurence_controller.ex, lib/dbservice_web/router.ex, lib/dbservice_web/swagger_schemas/session_occurence.ex, lib/dbservice_web/views/session_occurence_view.ex, priv/repo/seeds.exs, test/dbservice/sessions_test.exs, test/dbservice_web/controllers/session_occurence_controller_test.exs, test/support/fixtures/sessions_fixtures.ex
- Render session details with session occurrences
- Fixed spelling
=> Feat: Render session details with session occurrences

lib/dbservice/group_users.ex, lib/dbservice_web/controllers/group_user_controller.ex, lib/dbservice_web/router.ex
- This PR introduces an update function in the GroupUserController to provide type-specific handling when updating group_user and enrollment_record entries.
- The function now accepts a type parameter from the request, which is used to fetch and update the appropriate GroupUser and EnrollmentRecord entries.
=> Feat: Enhance GroupUser Update Function for Type-Specific Handling

.github/workflows/ci.yml, lib/dbservice_web.ex, lib/dbservice_web/gettext.ex, mix.exs
- Made changes in `gettext` file
- Updated elixir and erlang version
=> Hotfix: Failing CI

lib/dbservice/enrollment_records.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/router.ex
This PR introduces a new function update_user_enrollment_records in the StudentController to allow flexible updating of multiple fields in enrollment records based on provided parameters.
- Added a new function update_user_enrollment_records to the StudentController.
- Implemented logic to process any updateable fields passed in the params for enrollment records.
- Created a mechanism to filter out non-updateable fields (student_id and academic_year) from the update operation.
- Utilized the existing EnrollmentRecordView for consistent JSON rendering of updated records.
=> Feat: Add generic update_user_enrollment_records function to StudentController

lib/dbservice/users/student.ex, lib/dbservice_web/swagger_schemas/student.ex, lib/dbservice_web/views/student_view.ex, priv/repo/migrations/20240910071136_add_board_stream_to_student_table.exs
- Created migration to add `board_stream` in the student table
- Added `board_stream` in views, schema and swagger
=> Feat: Added board stream to student table

lib/dbservice/enrollment_records.ex, lib/dbservice/statuses.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/router.ex
- Some students have been incorrectly marked as "dropouts" in our system. We have implemented a process to reverse this mistake by removing the dropout status from both the enrollment records and the student table.
=> Feat: Added functionality to update ER

lib/dbservice/users/teacher.ex, lib/dbservice_web/swagger_schemas/teacher.ex, lib/dbservice_web/views/teacher_view.ex, priv/repo/migrations/20241015124806_add_column_to_teacher.exs
- Created migration to add `is_af_teacher` in teacher's table
- Updated teacher schema, views and swagger
=> Feat: Added `is_af_teacher` to teacher's table

lib/dbservice_web/controllers/group_user_controller.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/router.ex, lib/dbservice_web/views/group_user_view.ex, lib/dbservice_web/views/student_view.ex
- This pull request introduces new API endpoints that enables batch processing for adding students, their corresponding group-users, and enrollment records. s. Previously, this approach led to large time consumption when handling large datasets.
=> Feat: Batch Processing API for Students, Group-Users, and Enrollment Records

lib/dbservice_web/controllers/student_controller.ex
Minor adjustments to the code of batch process.
Original PR: #219
=> Batch process for student data addition

lib/dbservice_web/views/student_view.ex
=> Prod deployment: View Fixes

lib/dbservice_web/controllers/exam_controller.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/controllers/student_exam_record_controller.ex, lib/dbservice_web/swagger_schemas/student_exam_record.ex
This PR fixes issue #217.
Update the code wherever required to resolve the errors caused in swagger doc.
=> Updating Swagger doc to resolve errors

lib/dbservice_web/controllers/session_occurence_controller.ex
- Modified the function to accept session_ids as a query parameter and filter session occurrences based on the provided session IDs
=> Feat: Enhance session occurrence fetching logic

lib/dbservice/exams/student_exam_record.ex, lib/dbservice/student_exam_records.ex, lib/dbservice_web/controllers/student_exam_record_controller.ex, priv/repo/migrations/20241213130842_alter_student_exam_record_table.exs
- Made `date` field as nullable
- Modified create function to prevent duplicate records for same `student_id` and `application_number`
=> Fix: Student Exam Record

lib/dbservice/schools/school.ex
- Added af_school_category, district_code, district, state_code and state in the list of required fields
=> Feat: Updated required fields for school

lib/dbservice/grades.ex, lib/dbservice/grades/grade.ex, lib/dbservice_web/views/group_view.ex, priv/repo/migrations/20250104114947_add_grade_to_enrollment_record.exs
- Added migration to fetch grade information for all users and make an ER & group_user record for each user
=> Feat: Treat grade as a group

lib/dbservice/enrollment_record/enrollment_record.ex, lib/dbservice/enrollment_records.ex, lib/dbservice_web/controllers/enrollment_record_controller.ex, lib/dbservice_web/controllers/group_user_controller.ex, lib/dbservice_web/swagger_schemas/enrollment_record.ex, lib/dbservice_web/views/enrollment_record_view.ex, priv/repo/migrations/20250123110317_remove_grade_id_from_grade.exs
- Removed grade_id from schema, views, swagger and controllers
=> Feat: Removed grade_id from enrollment record

lib/dbservice/enrollment_record/enrollment_record.ex
Removed grade_id from the list of required fields
=> removed grade_id from required fields

lib/dbservice_web/controllers/group_user_controller.ex
=> Feat: Create ER for grade

lib/dbservice_web/views/resource_view.ex
- Return source with resource in JSON response
=> Feat: Render source with resource

lib/dbservice/users/student.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/swagger_schemas/student.ex, lib/dbservice_web/views/student_view.ex, priv/repo/migrations/20250623114448_add_apaar_id_to_student_table.exs
- Added APAAR ID in the student table
- Modified views, swagger, schema
- Removed unused `student_registration` function from swagger
=> Feat: Add APAAR ID to student

lib/dbservice/users/student.ex, lib/dbservice/users/user.ex, lib/dbservice/utils/util.ex
- https://www.notion.so/avantifellows/96ca4072573047a188ff79f0fb6d27fc?v=9984743585f04c49aff585547c4a29f6&p=17dd19b3111c80fda4c9eb94b0c8a79f&pm=s
- Added validation handler functions for category, gender and stream
=> Feat: Added field validations

lib/dbservice/utils/util.ex
=> Prod: Updation of valid streams

lib/dbservice/users.ex, lib/dbservice_web/controllers/student_controller.ex, lib/dbservice_web/router.ex
=> Feat: Get student by ID and group

lib/dbservice_web/controllers/group_session_controller.ex
=> Fix: Render Auth Group

lib/dbservice/colleges/college.ex, lib/dbservice_web/json/college_json.ex, lib/dbservice_web/swagger_schemas/college.ex, priv/repo/migrations/20250729120000_rename_district_code_to_district_in_college.exs
rename column name from district_code to district
=> (fix): alter table coloumn from district_code to district

lib/dbservice/constants/mappings.ex, lib/dbservice/data_import.ex, lib/dbservice/utils/import_worker.ex, lib/dbservice/utils/teacher_batch_assignment.ex, lib/dbservice_web/controllers/teacher_controller.ex, lib/dbservice_web/json/teacher_json.ex, lib/dbservice_web/live/import_live/new.ex, lib/dbservice_web/router.ex, lib/dbservice_web/swagger_schemas/teacher.ex
- Added endpoint for teacher batch assignment
- Added Liveview
=> feat: Add Teacher Batch Assignment functionality with LiveView integration

lib/dbservice/utils/util.ex
=> Prod deploy: Updated stream values

lib/dbservice/constants/mappings.ex
=> Prod deployment: Updated mappings

lib/dbservice/constants/mappings.ex, lib/dbservice/utils/import_worker.ex
- Accept student or apaar_id for student updation
=> Feat: Accept student or APAAR ID for student updation

lib/dbservice/resources.ex
- Function to update concept ids
=> Feat: Added function to update concept ids
