avantifellows/db-service

- lib/dbservice/sessions.ex
- lib/dbservice/users/student.ex
- lib/dbservice/users/teacher.ex
- lib/dbservice_web/views/session_occurence_view.ex
Targets #23 & #21
1. Added imports to avoid warnings when running phoenix server
2. Preloading users in the view so that it only loads when `_with_users.json` is called and it works for create session occurrence endpoint as well along with show and update
> #23 Warning fixes #21 association error fix

- config/dev.exs
- lib/dbservice/schools/enrollment_record.ex
- lib/dbservice/sessions/user_session.ex
- lib/dbservice/users.ex
- lib/dbservice/users/student.ex
- lib/dbservice/users/teacher.ex
- lib/dbservice_web/controllers/student_controller.ex
- lib/dbservice_web/router.ex
- lib/dbservice_web/views/student_view.ex
Requires #16 to be merged before
Targets #8 
1. Single endpoint where the API client can send both user and student details in the payload and the service will create a user and a student for that.
2. The errors for user and student validation will happen as it is
3. Fixes in `belongs_to` for several structs as I figured that we need to explicitly import all the dependencies in Elixir to make things work as expected
4. `show_with_user.json` for student response to also include associated user info
> #8 Single API for student & user registration

- lib/dbservice_web/controllers/student_controller.ex
- lib/dbservice_web/views/student_view.ex
- lib/dbservice_web/views/user_view.ex
- Added a check for `response_size` parameter in the query which provides an optimized response if value of `response_size` is set to `compact`.
- Output when response size = compact:
- Output without response size parameter:
> Addition of additional parameter in query

- lib/dbservice_web/views/enrollment_record_view.ex
Issue_id #74 
This PR addresses an issue where two fields, academic_year and board_medium, were missing from the response of the /enrollment-record endpoint. To fix this, I added these fields to the EnrollmentRecordView module and updated the render function accordingly.
> Fix issue with missing fields in enrollment_record response

- lib/dbservice_web/controllers/batch_controller.ex
- lib/dbservice_web/controllers/batch_program_controller.ex
- lib/dbservice_web/controllers/enrollment_record_controller.ex
- lib/dbservice_web/controllers/group_controller.ex
- lib/dbservice_web/controllers/group_session_controller.ex
- lib/dbservice_web/controllers/group_type_controller.ex
- lib/dbservice_web/controllers/program_controller.ex
- lib/dbservice_web/controllers/school_controller.ex
- lib/dbservice_web/controllers/session_controller.ex
- lib/dbservice_web/controllers/session_occurence_controller.ex
- lib/dbservice_web/controllers/student_controller.ex
- lib/dbservice_web/controllers/teacher_controller.ex
- lib/dbservice_web/controllers/user_controller.ex
- lib/dbservice_web/controllers/user_session_controller.ex
- lib/dbservice_web/views/group_session_view.ex
This pull request adds pagination to the index function in all controller. The offset and limit parameters are now used to control which subset of records is returned by the Ecto query, allowing clients to easily paginate through large result sets.
In addition, the function has been refactored to simplify the parameter handling and improve readability.
> Add pagination to all index function

- .gitignore
- docs/INSTALLATION.md
- lib/dbservice_web/controllers/session_controller.ex
This PR updates session controller GET request to enable the following:
- Get a list of sessions with `id` in descending order (using offset and limit)
- Get sessions with `session_id_is_null=true` 
So, a command like : `curl -X GET "http://localhost:4000/api/session?session_id_is_null=true&offset=0&limit=10" -H  "accept: application/json"` gives the latest ten sessions with id as null. 
This will be used by `quiz-creator` frontend to display sessions whose ID has not yet been generated. 
Additionally, this PR also updates local installation instructions for this repo.
> Update session controller to enable pagination

- lib/dbservice/batches/batch.ex
- lib/dbservice/session_schedules.ex
- lib/dbservice/sessions/session.ex
- lib/dbservice/sessions/session_schedule.ex
- lib/dbservice_web/controllers/session_schedule_controller.ex
- lib/dbservice_web/router.ex
- lib/dbservice_web/swagger_schemas/session_schedule.ex
- lib/dbservice_web/views/session_schedule_view.ex
- mix.exs
- priv/repo/migrations/20240212085413_create_session_schedule.exs
> Session schedule schema

- lib/dbservice_web/controllers/student_controller.ex
- lib/dbservice_web/plugs/authentication_middleware_plug.ex
- mix.exs
- Adding Observer CLI library to be dropped into any beam nodes, to be used to assist DevOps people diagnose problems in production nodes.
- Removed phoenix live dashboard from protected routes
- Removed user preload statement
> Feat: New library addition

- lib/dbservice_web/controllers/session_controller.ex
The is_quiz parameter allows filtering sessions based on whether the platform column is 'quiz' or not.
> Add is_quiz Filter to Filter by platform (Quiz or Not)

- lib/dbservice_web/controllers/user_controller.ex
- Renamed `batch` to `batch_id`
> Fix: Rename batch to batch_id

- lib/dbservice/utils/util.ex
- Updated `invalidate_future_date` function in Utils module to use DateTime for IST conversions and comparisons.
> Bugfix: Fix user-session timestamp validation for IST

- lib/dbservice/utils/util.ex
This PR fixes an issue in the `invalidate_future_date` function where a `FunctionClauseError` was raised due to a mismatch between `Date` and `DateTime` structs during comparison.
- Updated the `invalidate_future_date` function in `Dbservice.Utils.Util` to handle `Date` and `DateTime` structs appropriately.
> Fix: DateTime comparison Issue in `invalidate_future_date` function

- lib/dbservice_web/controllers/session_controller.ex
- handle sessions with platform = `null` as non-quiz in  is_quiz filter.
> Session is_quiz filter

- lib/dbservice/group_sessions.ex
- lib/dbservice_web/controllers/group_session_controller.ex
- lib/dbservice_web/controllers/student_controller.ex
- lib/dbservice_web/router.ex
- This PR moves the logic for retrieving auth group data from the portal-backend to the db-service. This change aims to optimize our API structure by reducing multiple API calls to a single call.
- Implemented new endpoint in db-service: `GET /api/group-session/session-auth-group`
- Added `get_auth_group_from_session` function in `GroupSessionController`
- Implemented logic to traverse from `session_id` to `auth_group` through related entities
- The new endpoint accepts a `session_id `as a query parameter
- The function chain traverses from `GroupSession `-> `Group `-> `Batch `-> `AuthGroup`
- Error handling has been implemented for cases where any entity in the chain is not found
> Get auth group from session id

- lib/dbservice_web/controllers/school_controller.ex
This PR introduces functionality to handle scenarios where an existing school does not have an associated user. If a school is found without a user, a new user will be created and associated with that school before updating the school details.
- Updated `update_existing_school_with_user` to check if `existing_school.user_id` is nil.
- If `user_id` is nil, a new user is created using `Users.create_user`
- The new user is then associated with the school, and the school details are updated.
- If `user_id` is not nil, the existing user is retrieved and the school details are updated accordingly.
> Added functionality to create user for existing school if user doesn't exist

- lib/dbservice/groups.ex
- lib/dbservice_web/controllers/student_controller.ex
- lib/dbservice_web/controllers/user_controller.ex
- lib/dbservice_web/router.ex
- lib/dbservice_web/swagger_schemas/student.ex
Created a new API endpoint for verifying student information. The endpoint allows for the validation of student and user data and group-user record against provided `student_id ` and `auth_group_id ` and other parameters.
1. Accepts a student ID and verification parameters.
2. Retrieves the student and associated user data.
3. Verifies the provided parameters against the student and user data.
4. Retrieves the group-user record using auth_group_id.
5. Returns response as true if verification parameters matches with data and group-user record exists else return false.
> verify-student endpoint in student controller

- lib/dbservice/group_users.ex
- lib/dbservice_web/controllers/group_user_controller.ex
This commit enhances the `update_by_type` functionality in the GroupUserController and addresses related issues:
1. Adds support for updating multiple batches per user while maintaining compatibility with single-association group types (like school or auth_group).
2. Fixes the KeyError caused by the :group association not being preloaded in the GroupUsers query.
3. Improves error handling and response formatting in the controller.
- Modified `get_group_users_by_user_id_and_type/2` in GroupUsers module to preload the :group association.
- Updated `update_by_type/2` in GroupUserController to handle both batch and non-batch group types differently.
- Implemented case-specific logic for selecting the correct GroupUser and EnrollmentRecord to update.
- Enhanced error handling to return …
> Refactor `update_by_type` to support updation of the provided batch and fix group preloading

- lib/dbservice_web/controllers/user_session_controller.ex
- lib/dbservice_web/router.ex
- This PR introduces functionality to clean up duplicate student records from the database by checking their session attendance before deletion. We verify if a student has attended at least one session before deciding to delete or retain their record.
> Feat: API to delete student from db

- lib/dbservice/enrollment_record/enrollment_record.ex
- lib/dbservice_web/controllers/group_user_controller.ex
- priv/repo/migrations/20241206075101_remove_academic_year_from_auth_group_er.exs
This PR addresses an issue with academic year handling for auth group enrollment records by:
- Removing academic_year for auth group during batch processing
- Updating the database to clear existing academic year values for auth groups
- Adding logic to prevent setting academic year for auth group enrollments
> Feat: Remove academic_year for auth_group enrollment records

- lib/dbservice_web/controllers/student_controller.ex
- This PR modifies the enrollment process to use a provided start_date parameter instead of automatically using the current timestamp.
Changes:
- Remove DateTime.utc_now() usage
- Add start_date parameter to enrollment functions
- Use provided start_date for new enrollment records
- Use same start_date when marking previous enrollments as inactive
This change requires the start_date parameter to be included in enrollment requests.
> Refactor: Use provided start_date for enrollment instead of current timestamp

- lib/dbservice_web/controllers/user_session_controller.ex
- lib/dbservice_web/router.ex
- This PR adds functionality to remove a specific batch mapping for a student. This is needed when a student is mapped to incorrect batches and we want to remove one of those mappings.
- Added new DELETE endpoint `/remove-batch/:student_id/:batch_id`
- Added batch lookup using batch_id (string)
- Implemented deletion of corresponding records from:
- group_user table (using group mapping)
- enrollment_record table
- Added transaction support to ensure data consistency
- Added proper error handling for various failure cases
The endpoint requires:
- student_id: Student's unique identifier
- batch_id: Batch's string identifier
Error handling covers:
- Student not found
- Batch not found 
- Missing user mapping
- Group mapping not found
Testing:
> Feat: API endpoint to remove specific batch mapping for a student

- lib/dbservice/statuses.ex
- lib/dbservice_web/controllers/student_controller.ex
- lib/dbservice_web/router.ex
- Introduced an API to update student's status
> Feat: API to update student's status

- lib/dbservice/enrollment_records.ex
- lib/dbservice_web/controllers/student_controller.ex
This PR enhances the way student grade changes are handled during enrollment. 
**Previously:**
- When enrolling a student, the system would create batch and status enrollment records but didn't properly track grade changes
- Grade information was stored in enrollment records and group_user table but wasn't consistently updated
- When a student's grade changed, historical grade data wasn't preserved
- The student record's grade_id field wasn't being updated during enrollment
**Now:**
- The system detects grade changes by comparing the current grade with the requested grade
- When grade changes are detected, a new grade-specific enrollment record is created
- Previous grade enrollment records are marked as not current with an end_date
- The student's grade_id field is properly updated in …
> Feat: Enhance student grade tracking and enrollment process

- lib/dbservice/batches/batch.ex
- lib/dbservice/grades/grade.ex
- lib/dbservice/programs/program.ex
- lib/dbservice/schools/school.ex
- lib/dbservice/users/student.ex
- lib/dbservice_web/swagger_schemas/batch.ex
- lib/dbservice_web/swagger_schemas/program.ex
- lib/dbservice_web/swagger_schemas/school.ex
- lib/dbservice_web/swagger_schemas/student.ex
- lib/dbservice_web/views/batch_view.ex
- lib/dbservice_web/views/program_view.ex
- lib/dbservice_web/views/school_view.ex
- lib/dbservice_web/views/student_view.ex
- priv/repo/migrations/20240930142432_update_tables_and_columns.exs
1. Moved `board_medium` from the school table to the student table and renamed it to `school_medium`
2. Added `af_medium` to the batch table
3. Added `model` to the program table
4. Added `is_current` to the program table
> Feat: Schema changes

- lib/dbservice_web/controllers/student_controller.ex
- Allow updates to any group_type
- Apply updates only to the fields explicitly passed in the params
- Conditionally update the status record (with group_type = "status" and is_current = true) only if the group_type is "batch"
Ops shared data to update batches for some students, but they provided the wrong academic_year. This change allows us to update only specific fields (like academic_year) for the enrollment records using student_id and group_id, without affecting other data.
> Fix: Funtionality to update user's enrollment records

- priv/repo/migrations/20250709065309_update_student_category.exs
This migration updates the category field in the student table for existing records where `physically_handicapped` is `true`:
- If the current category is `Gen-EWS`, it is changed to `PWD-EWS` (not `PWD-Gen-EWS`).
- For all other categories (except those already starting with PWD-), the value is updated by prepending PWD- (e.g., `Gen` becomes `PWD-Gen`, `OBC` becomes `PWD-OBC`, etc.).
- The migration includes a reversible down function to restore the original categories for affected students.
> Feat: Update Student Category for Physically Handicapped Students (PWD)

- lib/dbservice_web/controllers/session_occurence_controller.ex
This PR refactors the apply_time_filter/5 function in SessionOccurrenceController to correctly filter sessions based on their repeat_schedule.type value.
- Added a join with the sessions table to access repeat_schedule.
- Differentiated "today" filter logic:
- Continuous sessions → considered active if current_time is between start_time and end_time.
- Non-continuous sessions → considered active today if start_time falls within today’s date range.
> Feat: Optimize apply_time_filter/5 to handle continuous vs non-continuous sessions

- priv/repo/migrations/20250825075810_add_indexes_on_fk_and_lookup_fields.exs
- https://www.notion.so/avantifellows/ADR-Adding-Indexes-to-Foreign-Keys-and-Frequently-Queried-Fields-257d19b3111c801e8a12f8d84e89c4d0#257d19b3111c80959a7cf729ef8e7089
- Added B-Tree indexes to improve join and filter performance across core tables.
- Covers FK relationships and high-traffic lookup fields per ADR.
> Feat: Add indexes for foreign keys and frequently queried lookup fields

- lib/dbservice/constants/mappings.ex
- lib/dbservice/users.ex
- lib/dbservice/utils/import_worker.ex
This PR enhances the student data import functionality to provide more flexible identification options. Previously, student imports required a `student_id` field, but now they can accept either `student_id` or `apaar_id` (or both), making the system more adaptable to different data sources.
- **File**: `lib/dbservice/users.ex`
- **Change**: Added `get_student_by_id_or_apaar_id/1` function
- **Purpose**: Allows finding students by either identifier with priority given to `student_id` when both are present
- **File**: `lib/dbservice/utils/import_worker.ex`
- **Change**: Modified `process_student_record/1` to validate presence of either identifier
- **Purpose**: Ensures at least one identification field is provided before processing student records
- **File**: …
> Feat: Enhance student import validation to accept either student_id or apaar_id
